### ISSUE TITLE
Add "End Break" Button

### ISSUE THREAD

**Issue by SachinMittal1766** [Daksh777/TakeABreak#101] opened 2022-03-10 12:56 UTC
### Is your feature request related to a problem? Please describe.

If someone set timer of 10 min but want to end his/her break time in between. So we should provide a "End Break" button when timer is running.

### Describe the solution you'd like.

I am thinking of providing a "End Break" button when timer will be running. So that if a person wants he/she can get back to work. I am GSSOC Contributor.

### Describe alternatives you've considered.

NO

**Comment by Daksh777** [comment] 2022-03-10 13:37
Duplicate of #35

**Closed by Daksh777** 2022-03-10 13:37 UTC
Labels: enhancement
