### ISSUE TITLE
Title: after closing the (break) website timer does not stop 

### ISSUE THREAD

**Issue by rashita79** [Daksh777/TakeABreak#56] opened 2022-03-03 16:57 UTC
### Is your feature request related to a problem? Please describe.

after closing the (break) website timer does not stop , this will be an issue if a user wants to go to another website for a break with different time also the when a website is choosen then the next website is choosen with the same time break

### Describe the solution you'd like.

stopping the timer as soon as the website is closed or reloading the complete website automatically.

### Describe alternatives you've considered.

for accessing other website with the same website within the break period we should have a differrent timer for that.

**Comment by Daksh777** [comment] 2022-03-04 04:49
Duplicate of #3

**Closed by Daksh777** 2022-03-04 04:49 UTC
