### ISSUE TITLE
Title: Could have a button for stopping the break/pausing the break

### ISSUE THREAD

**Issue by AnishkaKesaria** [Daksh777/TakeABreak#35] opened 2022-03-01 19:03 UTC
### Is your feature request related to a problem? Please describe.

i) Say that someone doesn't want to continue their break and feels that he/she must go back to work.
ii) Also if someone has decided to have a total of 5 mins break in the one hour task. 

### Describe the solution you'd like.

i) A stop button could be added which redirects the user to the home page again.
ii) A pause button would do the job

### Describe alternatives you've considered.

Stop/Pause on the tab

**Comment by monurao123456** [comment] 2022-03-03 09:49
@Daksh777 
sir i want to work on this .
please assign it to me

**Comment by Daksh777** [comment] 2022-03-04 08:35
It is already assigned to @AnishkaKesaria, @monurao123456

**Comment by Daksh777** [comment] 2022-03-10 09:39
Any updates on this @AnishkaKesaria ?
It's been more than 7 days

**Comment by SachinMittal1766** [comment] 2022-03-10 13:43
Hey @Daksh777, It is more than 7 days. So if they are not working. Pls assign it to me.

**Comment by Daksh777** [comment] 2022-03-10 13:49
If they do not reply by tomorrow, I'll assign it to you @SachinMittal1766

**Comment by SachinMittal1766** [comment] 2022-03-12 03:20
Any Updates @Daksh777 ??

**Comment by Daksh777** [comment] 2022-03-12 13:10
You may work on it @SachinMittal1766

**Comment by vickyrules** [comment] 2022-04-02 08:30
@Daksh777 if the issue is still exist please assign it to me.

**Comment by vickyrules** [comment] 2022-04-02 13:45
@Daksh777  is there any pre -implemented code block for this feature or i have to make it from scratch .

**Comment by Daksh777** [comment] 2022-04-02 15:18
No @vickyrules, no pre-implemented code for any of these issues.

**Comment by vickyrules** [comment] 2022-04-02 16:20
@Daksh777 
what is this code doing.
https://github.com/Daksh777/TakeABreak/blob/68c922a52ddaab0a1edde3731975804c3570e045/scripts/main.js#L873-L908

**Comment by vickyrules** [comment] 2022-04-02 16:27
@Daksh777  where you want to put buttons to stop and pause,

**Comment by Anirban-1490** [comment] 2022-04-24 13:30
umm @Daksh777 is this issue still active , if yes the assign me this :)

**Comment by Daksh777** [comment] 2022-04-25 04:32
@vickyrules, would you like me to assign this issue to @Anirban-1490?

**Comment by vickyrules** [comment] 2022-04-25 06:11
> @vickyrules, would you like me to assign this issue to @Anirban-1490?

Go for it.

**Comment by Anirban-1490** [comment] 2022-04-25 10:13
Thanks will work on it :)

**Closed** 2022-05-04 15:59 UTC
Labels: enhancement, GSSoC22, Level2
