### ISSUE TITLE
Integrating a to-do list on homepage

### ISSUE THREAD

**Issue by MonarchGitHub** [Daksh777/TakeABreak#146] opened 2022-04-27 05:57 UTC
### Is your feature request related to a problem? Please describe.

I want to add a to-do list integration with the timer, I think it will enhance the user experience as well as the productivity of the user.

### Describe the solution you'd like.

I plan to integrate the widget seamlessly into the UI so that it won't stand out. 

### Describe alternatives you've considered.

I think the widget will be perfect in this section of the website.
<img width="968" alt="image" src="https://user-images.githubusercontent.com/74449136/165450823-341cb95c-8e40-46d9-9387-9e44f2988564.png">

**Comment by Daksh777** [comment] 2022-04-27 07:04
Duplicate of #136

**Closed by Daksh777** 2022-04-27 07:04 UTC
Labels: enhancement
