### ISSUE TITLE
Title: When user enters garbage value in custom time section  label:GSSoC22 

### ISSUE THREAD

**Issue by rashita79** [Daksh777/TakeABreak#30] opened 2022-03-01 13:51 UTC
### What happened?

When user enter any value in the custom section like if user enters "abc#3242" or "100000" then the website is prompting to enter the url to go for a break but instead it could have prompted an error message of "WRONG VALUE ENTERED" 

### How can we reproduce this bug?

When invalid custom time is written then their should be a proper prompt for wrong or invalid input instead of prompting it to the url box for input.

custom time could be of standard time selection so that user can easily select proper minutes , second ,hours or these combinations, instead of only minute .
Like if user want 1hour 38 minute break for binge watching because the movie time is 1hour and 38 minute so instead of converting this into minutes he can choose from the format like
TIME:
01 :38

**Comment by Girlwithasmile** [comment] 2022-03-01 14:00
If no one has been assigned then I would like to work on it under gssoc'22

**Comment by rashita79** [comment] 2022-03-01 14:05
I am willing to work on it as I raised that issue for GSSOC'2022

**Comment by Daksh777** [comment] 2022-03-01 16:27
Duplicate of #4

**Closed by Daksh777** 2022-03-01 16:27 UTC
Labels: bug
