### ISSUE TITLE
Enhancement of Scroll Bar

### ISSUE THREAD

**Issue by Simran2337** [Daksh777/TakeABreak#75] opened 2022-03-05 10:23 UTC
### Is your feature request related to a problem? Please describe.

The scroll bar looks odd at this website in such a way

### Describe the solution you'd like.

The scroll bar can be modified and look thin like standard websites

@Daksh777 if you find this useful you can assign it to me

![image](https://user-images.githubusercontent.com/54612637/156879190-715ac361-5f82-4c9a-9a22-472f18f23f9e.png)

**Comment by Daksh777** [comment] 2022-03-05 10:37
Duplicate of https://github.com/Daksh777/TakeABreak/issues/50

**Closed by Daksh777** 2022-03-05 10:37 UTC
Labels: enhancement
