### ISSUE TITLE
Adding an alert when the user adds an empty site link using the add site button.

### ISSUE THREAD

**Issue by rajaditya28** [Daksh777/TakeABreak#19] opened 2022-03-01 07:14 UTC
Currently, the site allows adding empty sites using the add site button. Also, inspite of the code having a http adder to site links that dont start with http, it doesn't seem to work as expected.

![Screenshot 2022-03-01 123918](https://user-images.githubusercontent.com/68824237/156121853-31cb9174-2795-4fdb-b778-13a0ca8dec0c.png)

![Screenshot 2022-03-01 124149](https://user-images.githubusercontent.com/68824237/156122229-c4ef6e2d-1e55-463e-8fbc-207b6c47358e.png)

Kindly assign me this issue @Daksh777 . I think I can work out a way to make these improvements.

**Comment by Daksh777** [comment] 2022-03-01 07:16
Good find, I'll assign the issue to you.

**Comment by rajaditya28** [comment] 2022-03-01 07:19
Thank you for assigning the issue !

**Comment by Sanghu01** [comment] 2022-03-01 11:13
I want to work on this project.

**Comment by Daksh777** [comment] 2022-03-01 11:35
@Sanghu01 The issue is already assigned to @rajaditya28, so I can not assign it to you

**Comment by Daksh777** [comment] 2022-03-01 13:26
To display errors, please use swal which we're using for other dialogues/popups @rajaditya28

**Comment by rajaditya28** [comment] 2022-03-01 14:55
Okay !

**Comment by rajaditya28** [comment] 2022-03-01 19:36
I have made the Pull request #36 .
Kindly review it and merge the PR.
Thank You !!

**Closed** 2022-03-02 16:34 UTC
Labels: GSSoC22, Level1
